type Event {
  result: String
}

type Todo {
  task: String
  done: Boolean
  id: String!
}

type Query {
  getTodos: [Todo]
}

input TodoInput {  
  task: String
  done: Boolean
  id: String!
}

type Mutation {
  addTodo(todo: TodoInput): Event
  deleteTodo(id: String): Event
}